repos:
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv/Scripts/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
      - id: make migrations
        name: make migrations
        entry: bash -c '.venv/Scripts/python pixmessages/manage.py makemigrations api; git add pixmessages/api/migrations'
        language: system
        pass_filenames: false
        stages: [commit]